### ISSUE TITLE
phpBB validation

### ISSUE THREAD

**Issue by Galixte** [oneall/social-login-phpbb#36]
Hi @SchlesserClaude,

did you submitted your extension to the phpBB.com validation like your MOD: https://www.phpbb.com/customise/db/mod/oa_social_login/ ?

**Comment by SchlesserClaude** [comment]
Yes, I submitted the first version to phpBB.com. The first time it wasn't correctly formatted and got refused after 3 months of waiting. I then resubmitted it with the correct formatting and it took once again 3 months before it was approved.

We update the plugin very often, so waiting times of several months make no sense. We no longer submit new version to phpBB.com as they plugin is already outdated when it gets accepted.

**Comment by SiteSplat** [comment]
Yup some dreadful stories from the phpBB validation system. I believe its more of a problem due to certain individual there that just don't want to support certain type of MODs/Extension for whatever reasons. 

I too am one of those developers who submitted for validation and waited for months before even getting an answer that would make sense at all. I had to follow up with many emails to get a bit of information  and just got frustrated. Then you see validation like a "moon calendar" LOL and many other along that line so you can really understand what they seem to like to have in their Database...

In any case, don't mind the customization database and follow this active projects on Github or the original developers sites which is where you find the good projects. ;)

PS. if you are looking for premium theme (I support OneAll integration as well ) look here: http://themeforest.net/user/themesplat/portfolio?ref=ThemeSplat

OneAll and custom icons:
https://gyazo.com/7022bb9197e91e8a7b672ee76689ff16.png

Cheers!
Dave

**Comment by ForumHulp** [comment]
Hello Claus,

I really can understand you. I also have this problem. Waiting for more then a year to get our "Upload extensions" validated. Everytime there is something else, it gives me more the feeling they don't want this extension. Last extension emailonbirthday took 3 month for the first answer came. Textual problems, what are we talking about. It should be about security and this kind of things. Asking to embed and not use globals in listener. But this is not possible because the way how they scripted acp modules. 
Bugs send in at heir tracker stays open and nothing happens.

Anyway I also stopped with sending in for validating and people can download at <a href="https://github.com/ForumHulp">Github</a> or <a href="http://forumhulp.com">ForumHulp.com</a>

**Comment by SchlesserClaude** [comment]
The plugin is now also available here:
https://www.phpbb.com/customise/db/extension/social_login/
